import Head from 'next/head';
import { Landing } from '../components/contract/landing';

export default function Home() {
  return (
    <div className={''}>
      <Head>
        <title>Create-Web3 App</title>
        <meta name="description" content="Generated by npx create-web3" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <p className="font-light shadow-[0_35px_60px_-15px_rgba(25, 152, 178, 0.5)] p-2 landing-text text-xl text-white">DEGEN BLACKJACK</p>
        <Landing />
      </main>
    </div>
  );
}
