import Head from "next/head";


export const Landing = () => {
  return (
    <div className={'flex flex-col flex-1 items-center pt-4 bg-landing'}>
      <Head>
        <title>Create-Web3 App</title>
        <meta name="description" content="Generated by npx create-web3" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative min-h-[75vh] w-2/3 body-container rounded-sm">
        <a href="/play" className="landing-text absolute bottom-10 right-10 inline-block text-lg group">
          <span className="relative z-10 block px-5 py-3 overflow-hidden font-medium leading-tight text-gray-800 transition-colors duration-300 ease-out border-2 border-gray-900 rounded-lg group-hover:text-white">
            <span className="absolute inset-0 w-full h-full px-5 py-3 rounded-lg bg-gray-50"></span>
            <span className="absolute left-0 w-48 h-48 -ml-2 transition-all duration-300 origin-top-right -rotate-90 -translate-x-full translate-y-12 bg-gray-900 group-hover:-rotate-180 ease"></span>
            <span className="relative button-style">PLAY NOW</span>
          </span>
          <span className="absolute bottom-0 right-0 w-full h-12 -mb-1 -mr-1 transition-all duration-200 ease-linear bg-gray-900 rounded-lg group-hover:mb-0 group-hover:mr-0" data-rounded="rounded-lg"></span>
        </a>
      </div>
      <div className="text-white flex w-2/3 justify-between gap-10">
        <div className="mt-2">
          <p className="text-2xl">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do</p>
          <p className="text-md">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do</p>
          <p className="text-md">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do</p>
        </div>
        <div className="mt-2">
          <p className="text-2xl">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do</p>
          <p className="text-md">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do</p>
          <p className="text-md">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do</p>
        </div>
      </div>
    </div>
  );
}
